# noinspection SpellCheckingInspection
CONSOLA = './res/font/consola.ttf'
# noinspection SpellCheckingInspection
CONSOLAB = './res/font/consolab.ttf'
# noinspection SpellCheckingInspection
CONSOLAI = './res/font/consolai.ttf'
# noinspection SpellCheckingInspection
CONSOLAZ = './res/font/consolaz.ttf'
# noinspection SpellCheckingInspection
DALMOORI = './res/font/dalmoori.ttf'
